name: smart_home_automation
description: A smart home automation app with MQTT and voice control.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  avatar_glow: ^2.0.2  
  highlight_text: ^1.8.0
  mqtt_client: ^9.7.2
  shared_preferences: ^2.5.2
  speech_to_text: ^7.0.0
  tflite_flutter: ^0.11.0
  audioplayers: ^6.4.0
  wiz: ^0.0.5
  fl_chart: ^1.1.0
  http: ^0.13.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true